[["atomic_lib::commit::Commit::apply_opts"]]
marker = "commit"
on_argument = [0]

[["atomic_lib::commit::Commit::into_resource"]]
marker = "resource"
on_return = true

[["atomic_lib::storelike::Storelike::get_resource"]]
marker = "resource"
on_return = true

[["atomic_lib::hierarchy::check_write"]]
marker = "check_rights"
on_argument = [1]

[["atomic_lib::resources::Resource::set_propval"]]
marker = "new_resource"
on_argument = [1]

[["atomic_lib::storelike::Storelike::add_resource"]]
marker = "sink"
on_argument = [1]
