#####################################################################
# General settings
#####################################################################

stat-refresh-interval = "500ms"
paralegal-home-dir = "/home/jadam/research/paralegal"
# Tried 10 min as well but didn't improve
pdg-timeout = "5min"

#####################################################################
# Defition of use case applications
#####################################################################

[app-config.lemmy]
source-dir = "case-studies/lemmy-unhacked"
external-annotations = "external-annotations.toml"

[app-config.plume]
source-dir = "case-studies/plume"
external-annotations = "external-annotations.toml"
flow-args = ["--target", "plume-models"]
cargo-args = ["--no-default-features", "--features", "postgres"]

[app-config.websubmit]
source-dir = "case-studies/websubmit"
external-annotations = "baseline-external-annotations.toml"

[app-config.freedit]
source-dir = "case-studies/freedit"
flow-args = ["--relaxed"]
cargo-args = ["--lib"]
external-annotations = "external-annotations.toml"

[app-config.atomic-data]
source-dir = "case-studies/atomic-server"
external-annotations = "external-annotations.toml"
flow-args = ["--target", "atomic_lib"]
cargo-args = ["--lib", "--features", "db"]

[app-config.atomic-data.version-override.proc-macro2]
replacement = "1.0.78"
original = "1"

[app-config.hyperswitch]
source-dir = "case-studies/hyperswitch"
external-annotations = "external-annotations.toml"
flow-args = ["--target", "router"]
cargo-args = ["--lib"]

[app-config.hyperswitch.env]
LD_LIBRARY_PATH = "/home/jadam/.rustup/toolchains/nightly-2023-08-25-x86_64-unknown-linux-gnu/lib"

[app-config.contile]
source-dir = "case-studies/contile"
external-annotations = "external-annotations.toml"
cargo-args = ["--lib"]

[app-config.mcaptcha]
source-dir = "case-studies/mCaptcha"
flow-args = ["--target", "mcaptcha"]
external-annotations = "external-annotations.toml"

[app-config.roll-forward-atomic]
# Must point to a directory containing the
# https://github.com/atomicdata-dev/atomic-server git repository
#
# If the directory does not exist, the runner will to auto-clone. The parent
# directory must exist however
source-dir = "../../clones/atomic-server"
clone = "https://github.com/atomicdata-dev/atomic-server"
flow-args = [
    "--target",
    "atomic_lib",
    "--analyze",
    "crate::commit::Commit::apply_opts",
    "--relaxed",
]
cargo-args = ["--lib", "--features", "db"]

[app-config.roll-forward-atomic.env]
RUSTUP_TOOLCHAIN = "1.75"

#####################################################################
# Experiment 1: CI environment
#####################################################################

[[experiment.ci]]
mode = "case-study"
application = "plume"
policy-mode = "unified"

[[experiment.ci]]
mode = "case-study"
application = "freedit"
policy-mode = "unified"

[[experiment.ci]]
mode = "case-study"
application = "websubmit"
policy-mode = "unified"

[[experiment.ci]]
mode = "case-study"
application = "atomic-data"
policy-mode = "unified"

[[experiment.ci]]
mode = "case-study"
application = "lemmy"
new-version = "api"
controller-run-mode = "all"
bugs = ["bug4"]

[[experiment.ci]]
mode = "case-study"
application = "lemmy"
new-version = "api-crud"
controller-run-mode = "all"
bugs = ["bug4"]

[[experiment.ci]]
mode = "case-study"
application = "hyperswitch"
# Limiting policies for now, because only these actually make sense
policies = ["card-storage", "apikey-storage"]
policy-mode = "unified"

[[experiment.ci]]
mode = "case-study"
application = "contile"
policy-mode = "unified"

[[experiment.ci]]
mode = "case-study"
application = "mcaptcha"
policy-mode = "unified"

#####################################################################
# Experiment 1.5: Extra Contile run for the CI experiment
#####################################################################

# Special second contile run with a +1 depth to deal with the false positive.
[[experiment.contile-extra]]
mode = "case-study"
application = "contile"
policy-mode = "unified"
k-depth = 1

#####################################################################
# Experiment 2: IDE environment
#####################################################################

[[experiment.ide]]
mode = "case-study"
application = "plume"
policy-mode = "unified"
include = ["crate"]

[[experiment.ide]]
mode = "case-study"
application = "freedit"
policy-mode = "unified"
include = ["crate"]

[[experiment.ide]]
mode = "case-study"
application = "websubmit"
policy-mode = "unified"
include = ["crate"]

[[experiment.ide]]
mode = "case-study"
application = "atomic-data"
policy-mode = "unified"
include = ["crate"]

[[experiment.ide]]
mode = "case-study"
application = "lemmy"
new-version = "api"
controller-run-mode = "all"
bugs = ["bug4"]
include = [
    "crate",
    "lemmy_api_common",
    "lemmy_api_crud",
    "lemmy_api",
    "lemmy_apub",
    "lemmy_db_schema",
    "lemmy_db_views",
    "lemmy_db_views_actor",
    "lemmy_db_views_moderator",
    "lemmy_routes",
    "lemmy_utils",
    "lemmy_websocket",
]

[[experiment.ide]]
mode = "case-study"
application = "lemmy"
new-version = "api-crud"
controller-run-mode = "all"
bugs = ["bug4"]
include = [
    "crate",
    "lemmy_api_common",
    "lemmy_api_crud",
    "lemmy_api",
    "lemmy_apub",
    "lemmy_db_schema",
    "lemmy_db_views",
    "lemmy_db_views_actor",
    "lemmy_db_views_moderator",
    "lemmy_routes",
    "lemmy_utils",
    "lemmy_websocket",
]

[[experiment.ide]]
mode = "case-study"
application = "hyperswitch"
policies = ["card-storage", "apikey-storage"]
policy-mode = "unified"
include = ["crate"]

[[experiment.ide]]
mode = "case-study"
application = "contile"
policy-mode = "unified"
include = ["crate"]

[[experiment.ide]]
mode = "case-study"
application = "mcaptcha"
policy-mode = "unified"
include = ["crate"]

#####################################################################
# Experiment 3: No Adaptive Depth
#####################################################################

[[experiment.adaptive-depth]]
mode = "case-study"
application = "plume"
policy-mode = "unified"
adaptive-depth = false
k-depth = 19

[[experiment.adaptive-depth]]
mode = "case-study"
application = "freedit"
policy-mode = "unified"
adaptive-depth = false
k-depth = 6

[[experiment.adaptive-depth]]
mode = "case-study"
application = "websubmit"
policy-mode = "unified"
adaptive-depth = false
k-depth = 14

[[experiment.adaptive-depth]]
mode = "case-study"
application = "atomic-data"
policy-mode = "unified"
adaptive-depth = false
k-depth = 4

[[experiment.adaptive-depth]]
mode = "case-study"
lemmy-controller-run-mode = "all"
application = "lemmy"
policy-mode = "unified"
adaptive-depth = false
bugs = ["bug4"]
new-version = "api"
k-depth = 24

[[experiment.adaptive-depth]]
mode = "case-study"
lemmy-controller-run-mode = "all"
application = "lemmy"
policy-mode = "unified"
adaptive-depth = false
bugs = ["bug4"]
new-version = "api-crud"
k-depth = 24

[[experiment.adaptive-depth]]
mode = "case-study"
application = "contile"
policy-mode = "unified"
adaptive-depth = false
k-depth = 6

[[experiment.adaptive-depth]]
mode = "case-study"
application = "hyperswitch"
policies = ["card-storage", "apikey-storage"]
policy-mode = "unified"
adaptive-depth = false
k-depth = 11

[[experiment.adaptive-depth]]
mode = "case-study"
application = "mcaptcha"
policy-mode = "unified"
adaptive-depth = false
k-depth = 3

#####################################################################
# Experiment 4: Roll Forward
#####################################################################

[[experiment.atomic-roll-forward]]
mode = "roll-forward"
application = "atomic-data"
app-config-override = "roll-forward-atomic"

[[experiment.atomic-roll-forward.cutoff]]
commit = "79c9a91ae734ddd253d162a268de2a0365befcd7"
expectation = "pass"
external-annotations = "../../research/paralegal-bench/roll-forward/atomic/external-annotations.toml"

[[experiment.atomic-roll-forward.cutoff]]
commit = "e0cf2d1b90a23fc817d2529d309e5b67be42515b"
expectation = "pass"
external-annotations = "../../research/paralegal-bench/roll-forward/atomic/external-annotations.toml"

[[experiment.atomic-roll-forward.cutoff]]
commit = "51a665138875e2ef41c10e952b34c9d7eb5d5b79"
expectation = "pass"
external-annotations = "../../research/paralegal-bench/roll-forward/atomic/aba49fefb6e6e7def4faed4542b3436a358ef56f-external-annotations.toml"

# Skipping this range of 73 commits, because they don't compile (even with
# regular rustc, this is not a Paralegal issue). See
# https://www.notion.so/justus-adam/Roll-forward-experiment-on-5706ecdd8c7045ca9f3a9e3a4603e2fe?pvs=4
# for more information
[[experiment.atomic-roll-forward.cutoff]]
commit = "8523e091e3e2cf9d3ac6067e1908b52ac5ace2a2"

[[experiment.atomic-roll-forward.cutoff]]
commit = "1b9aee9cbac33b3636ebf6153f4d866b4c310fe4"
expectation = "pass"
external-annotations = "../../research/paralegal-bench/roll-forward/atomic/aba49fefb6e6e7def4faed4542b3436a358ef56f-external-annotations.toml"

# Skipping 8 commits that don't compile with rustc. This is not a Paralegal
# issue. See
# https://www.notion.so/justus-adam/Roll-forward-experiment-on-5706ecdd8c7045ca9f3a9e3a4603e2fe?pvs=4
# for more information
[[experiment.atomic-roll-forward.cutoff]]
commit = "83f8f4f411b8a502f9e122a470629ab15ce29adc"

[[experiment.atomic-roll-forward.cutoff]]
commit = "aba49fefb6e6e7def4faed4542b3436a358ef56f"
external-annotations = "../../research/paralegal-bench/roll-forward/atomic/aba49fefb6e6e7def4faed4542b3436a358ef56f-external-annotations.toml"
expectation = "pass"

[[experiment.atomic-roll-forward.cutoff]]
commit = "46a503adbfc52678c97e52f6e8cfaf541aa6492d"
external-annotations = "../../research/paralegal-bench/roll-forward/atomic/9745069392e25d70cf159fadcab6d2c22949fa49-external-annotations.toml"
expectation = "pass"

[[experiment.atomic-roll-forward.cutoff]]
commit = "9745069392e25d70cf159fadcab6d2c22949fa49"
external-annotations = "../../research/paralegal-bench/roll-forward/atomic/9745069392e25d70cf159fadcab6d2c22949fa49-external-annotations.toml"
expectation = "fail"

#####################################################################
# Experiment 5: Per-Controller Time
#####################################################################

[[experiment.per-controller-time]]
mode = "case-study"
application = "plume"
policy-mode = "unified"
controller-run-mode = "all-separate"

[[experiment.per-controller-time]]
mode = "case-study"
application = "freedit"
policy-mode = "unified"
controller-run-mode = "all-separate"

[[experiment.per-controller-time]]
mode = "case-study"
application = "websubmit"
policy-mode = "unified"
controller-run-mode = "all-separate"

[[experiment.per-controller-time]]
mode = "case-study"
application = "atomic-data"
policy-mode = "unified"
controller-run-mode = "all-separate"

[[experiment.per-controller-time]]
mode = "case-study"
application = "lemmy"
policy-mode = "unified"
bugs = ["bug4"]
controller-run-mode = "all-separate"
new-version = "api"

[[experiment.per-controller-time]]
mode = "case-study"
application = "lemmy"
policy-mode = "unified"
bugs = ["bug4"]
controller-run-mode = "all-separate"
new-version = "api-crud"

[[experiment.per-controller-time]]
mode = "case-study"
application = "hyperswitch"
# Limiting policies for now, because only these actually make sense
policies = ["card-storage", "apikey-storage"]
policy-mode = "unified"
controller-run-mode = "all-separate"

[[experiment.per-controller-time]]
mode = "case-study"
application = "contile"
# Otherwise we overtaint and don't pass the non-bug
policy-mode = "unified"
controller-run-mode = "all-separate"

[[experiment.per-controller-time]]
mode = "case-study"
application = "mcaptcha"
policy-mode = "unified"
controller-run-mode = "all-separate"

#####################################################################
# Experiment 6: Total Runtime, including dependency handling
#####################################################################

[[experiment.total-runtime]]
mode = "case-study"
application = "plume"
policy-mode = "unified"
clean = true

[[experiment.total-runtime]]
mode = "case-study"
application = "freedit"
policy-mode = "unified"
clean = true

[[experiment.total-runtime]]
mode = "case-study"
application = "websubmit"
policy-mode = "unified"
clean = true

[[experiment.total-runtime]]
mode = "case-study"
application = "atomic-data"
policy-mode = "unified"
clean = true

[[experiment.total-runtime]]
mode = "case-study"
application = "lemmy"
new-version = "api"
controller-run-mode = "all"
bugs = ["bug4"]
clean = true

[[experiment.total-runtime]]
mode = "case-study"
application = "lemmy"
new-version = "api-crud"
controller-run-mode = "all"
bugs = ["bug4"]
clean = true

[[experiment.total-runtime]]
mode = "case-study"
application = "hyperswitch"
policies = ["card-storage", "apikey-storage"]
policy-mode = "unified"
clean = true

[[experiment.total-runtime]]
mode = "case-study"
application = "contile"
policy-mode = "unified"
clean = true

[[experiment.total-runtime]]
mode = "case-study"
application = "mcaptcha"
policy-mode = "unified"
clean = true
