stat-refresh-interval = "500ms"
paralegal-home-dir = "/home/jadam/research/paralegal"
# Bumped because lemmy without adaptive depth takes ~10min in analysis
pdg-timeout = "10min"

[app-config.lemmy]
source-dir = "case-studies/lemmy-unhacked"
external-annotations = "external-annotations.toml"

[app-config.plume]
source-dir = "case-studies/plume"
external-annotations = "external-annotations.toml"
flow-args = ["--target", "plume-models"]
cargo-args = ["--no-default-features", "--features", "postgres"]

[app-config.websubmit]
source-dir = "case-studies/websubmit"
external-annotations = "baseline-external-annotations.toml"

[app-config.freedit]
source-dir = "case-studies/freedit"
cargo-args = ["--lib"]
external-annotations = "external-annotations.toml"

[app-config.atomic-data]
source-dir = "case-studies/atomic-server"
external-annotations = "external-annotations.toml"
flow-args = ["--target", "atomic_lib"]
cargo-args = ["--lib", "--features", "db"]

[app-config.atomic-data.version-override.proc-macro2]
replacement = "1.0.78"
original = "1"

[app-config.hyperswitch]
source-dir = "case-studies/hyperswitch"
external-annotations = "external-annotations.toml"
flow-args = ["--target", "router"]
cargo-args = ["--lib"]

[app-config.hyperswitch.env]
LD_LIBRARY_PATH = "/home/jadam/.rustup/toolchains/nightly-2023-08-25-x86_64-unknown-linux-gnu/lib"

[app-config.contile]
source-dir = "case-studies/contile"
external-annotations = "external-annotations.toml"
cargo-args = ["--lib"]

[app-config.mcaptcha]
source-dir = "case-studies/mCaptcha"
flow-args = ["--target", "mcaptcha"]
external-annotations = "external-annotations.toml"


[[experiment.case-studies]]
mode = "case-study"
application = "freedit"
policy-mode = "unified"
adaptive-depth = false
k-depth = 6

[[experiment.case-studies]]
mode = "case-study"
application = "atomic-data"
policy-mode = "unified"
k-depth = 4
adaptive-depth = false

[[experiment.case-studies]]
mode = "case-study"
application = "mcaptcha"
policy-mode = "unified"
adaptive-depth = false
k-depth = 3

[[experiment.case-studies]]
mode = "case-study"
application = "contile"
# Otherwise we overtaint and don't pass the non-bug
policy-mode = "unified"
adaptive-depth = false
k-depth = 6

[[experiment.case-studies]]
mode = "case-study"
application = "websubmit"
policy-mode = "unified"
k-depth = 14
adaptive-depth = false

[[experiment.case-studies]]
mode = "case-study"
lemmy-controller-run-mode = "all"
application = "lemmy"
policy-mode = "unified"
bugs = ["bug4"]
new-version = "api"
adaptive-depth = false
k-depth = 24

[[experiment.case-studies]]
mode = "case-study"
lemmy-controller-run-mode = "all"
application = "lemmy"
policy-mode = "unified"
bugs = ["bug4"]
new-version = "api-crud"
adaptive-depth = false
k-depth = 24

# Does not run on this machine sadly
[[experiment.case-studies]]
mode = "case-study"
application = "hyperswitch"
# Limiting policies for now, because only these actually make sense
policies = ["card-storage", "apikey-storage"]
policy-mode = "unified"
adaptive-depth = false
k-depth = 11

[[experiment.case-studies]]
mode = "case-study"
application = "plume"
policy-mode = "unified"
adaptive-depth = false
k-depth = 19
