
stat-refresh-interval = "500ms"
paralegal-home-dir = "../paralegal"
# Bumped because lemmy without adaptive depth takes ~10min in analysis
pdg-timeout = "15min"

[app-config.atomic-data]
source-dir = "case-studies/atomic-server"
external-annotations = "external-annotations.toml"
flow-args = ["--target", "atomic_lib", "--relaxed"]
cargo-args = ["--lib", "--features", "db"]


[app-config.roll-forward-atomic]
# Must point to a directory containing the
# https://github.com/atomicdata-dev/atomic-server git repository
#
# If the directory does not exist, the runner will to auto-clone. The parent
# directory must exist however
source-dir = "../../clones/atomic-server"
clone = "https://github.com/atomicdata-dev/atomic-server"
flow-args = [
    "--target",
    "atomic_lib",
    "--analyze",
    "crate::commit::Commit::apply_opts",
    "--relaxed",
]
cargo-args = ["--lib", "--features", "db"]

[app-config.roll-forward-atomic.env]
RUSTUP_TOOLCHAIN = "1.75"

[[experiment.atomic-roll-forward]]
mode = "roll-forward"
application = "atomic-data"
app-config-override = "roll-forward-atomic"

[[experiment.atomic-roll-forward.cutoff]]
commit = "79c9a91ae734ddd253d162a268de2a0365befcd7"
expectation = "pass"
external-annotations = "../../research/paralegal-bench/roll-forward/atomic/external-annotations.toml"

[[experiment.atomic-roll-forward.cutoff]]
commit = "e0cf2d1b90a23fc817d2529d309e5b67be42515b"
expectation = "pass"
external-annotations = "../../research/paralegal-bench/roll-forward/atomic/external-annotations.toml"

[[experiment.atomic-roll-forward.cutoff]]
commit = "51a665138875e2ef41c10e952b34c9d7eb5d5b79"
expectation = "pass"
external-annotations = "../../research/paralegal-bench/roll-forward/atomic/aba49fefb6e6e7def4faed4542b3436a358ef56f-external-annotations.toml"

# Skipping this range of 73 commits, because they don't compile (even with
# regular rustc, this is not a Paralegal issue). See
# https://www.notion.so/justus-adam/Roll-forward-experiment-on-5706ecdd8c7045ca9f3a9e3a4603e2fe?pvs=4
# for more information
[[experiment.atomic-roll-forward.cutoff]]
commit = "8523e091e3e2cf9d3ac6067e1908b52ac5ace2a2"

[[experiment.atomic-roll-forward.cutoff]]
commit = "1b9aee9cbac33b3636ebf6153f4d866b4c310fe4"
expectation = "pass"
external-annotations = "../../research/paralegal-bench/roll-forward/atomic/aba49fefb6e6e7def4faed4542b3436a358ef56f-external-annotations.toml"

# Skipping 8 commits that don't compile with rustc. This is not a Paralegal
# issue. See
# https://www.notion.so/justus-adam/Roll-forward-experiment-on-5706ecdd8c7045ca9f3a9e3a4603e2fe?pvs=4
# for more information
[[experiment.atomic-roll-forward.cutoff]]
commit = "83f8f4f411b8a502f9e122a470629ab15ce29adc"

[[experiment.atomic-roll-forward.cutoff]]
commit = "aba49fefb6e6e7def4faed4542b3436a358ef56f"
external-annotations = "../../research/paralegal-bench/roll-forward/atomic/aba49fefb6e6e7def4faed4542b3436a358ef56f-external-annotations.toml"
expectation = "pass"

[[experiment.atomic-roll-forward.cutoff]]
commit = "46a503adbfc52678c97e52f6e8cfaf541aa6492d"
external-annotations = "../../research/paralegal-bench/roll-forward/atomic/9745069392e25d70cf159fadcab6d2c22949fa49-external-annotations.toml"
expectation = "pass"

[[experiment.atomic-roll-forward.cutoff]]
commit = "9745069392e25d70cf159fadcab6d2c22949fa49"
external-annotations = "../../research/paralegal-bench/roll-forward/atomic/9745069392e25d70cf159fadcab6d2c22949fa49-external-annotations.toml"
expectation = "fail"
