stat-refresh-interval = "500ms"
paralegal-home-dir = "../paralegal"
pdg-timeout = "10min"

[app-config.lemmy]
source-dir = "case-studies/lemmy"
flow-args = ["--target", "lemmy_api"]
external-annotations = "external-annotations.toml"

[app-config.plume]
source-dir = "case-studies/plume"
external-annotations = "external-annotations.toml"
flow-args = ["--target", "plume-models"]
cargo-args = ["--no-default-features", "--features", "postgres"]

[app-config.websubmit]
source-dir = "case-studies/websubmit"
external-annotations = "baseline-external-annotations.toml"
cargo-args = ["--features", "v-ann-baseline"]

[app-config.websubmit-lib]
source-dir = "case-studies/websubmit"
external-annotations = "lib-external-annotations.toml"
cargo-args = ["--features", "v-ann-lib"]

[app-config.websubmit-strict]
source-dir = "case-studies/websubmit"
external-annotations = "strict-external-annotations.toml"
cargo-args = ["--features", "v-ann-strict"]

[app-config.freedit]
source-dir = "case-studies/freedit"
cargo-args = ["--lib"]
external-annotations = "external-annotations.toml"

[app-config.atomic-data]
source-dir = "case-studies/atomic-server"
external-annotations = "external-annotations.toml"
flow-args = ["--target", "atomic_lib"]
cargo-args = ["--lib", "--features", "db"]

[app-config.atomic-data.version-override.proc-macro2]
replacement = "1.0.78"
original = "1"

[app-config.hyperswitch]
source-dir = "case-studies/hyperswitch"
external-annotations = "external-annotations.toml"
flow-args = ["--target", "--router"]
cargo-args = ["--lib"]

[app-config.original-plume]
# Must point to a directory containing the https://github.com/Plume-org/Plume
# git repository
source-dir = "../../clones/Plume"
external-annotations = "../../research/dfpp-verification/roll-forward/original-plume-external-annotations.toml"
flow-args = [
    "--target",
    "plume-models",
    "--analyze",
    "crate::users::User::delete",
]
cargo-args = ["--no-default-features", "--features", "postgres"]


[app-config.original-plume.version-override.proc-macro2]
replacement = "1.0.78"
original = "1"

[app-config.original-atomic-data]
# Must point to a directory containing the
# https://github.com/atomicdata-dev/atomic-server git repository
source-dir = "../../clones/atomic-server"
external-annotations = "../../research/dfpp-verification/roll-forward/atomic/external-annotations.toml"
flow-args = [
    "--target",
    "atomic_lib",
    "--analyze",
    "crate::commit::Commit::apply_opts",
]
cargo-args = ["--lib", "--features", "db"]

[app-config.original-atomic-data.version-override.proc-macro2]
replacement = "1.0.78"
original = "1"

[[experiment.case-studies]]
mode = "case-study"
application = "lemmy"

[[experiment.case-studies]]
mode = "case-study"
application = "plume"

[[experiment.case-studies]]
mode = "case-study"
application = "freedit"

[[experiment.case-studies]]
mode = "case-study"
application = "websubmit"

[[experiment.case-studies]]
mode = "case-study"
application = "atomic-data"

# Need to debug the policy/app
# [[experiment.case-studies]]
# mode = "case-study"
# application = "hyperswitch"

[[experiment.adaptive-depth]]
mode = "case-study"
application = "lemmy"
adaptive-depth = false

[[experiment.ablation]]
mode = "ablation"
application = "websubmit"
feature-space-success = ["edit-del-1-a", "edit-del-2-a", "edit-del-3-a"]
feature-space-fail = [
    "edit-del-1-b",
    "edit-del-1-c",
    "edit-del-2-b",
    "edit-del-2-c",
    "edit-del-3-b",
    "edit-del-3-c",
]
policies = ["deletion"]

[[experiment.ablation]]
mode = "ablation"
application = "websubmit"
app-config-override = "websubmit-lib"
feature-space-success = ["edit-del-1-a", "edit-del-2-a", "edit-del-3-a"]
feature-space-fail = [
    "edit-del-1-b",
    "edit-del-1-c",
    "edit-del-2-b",
    "edit-del-2-c",
    "edit-del-3-b",
    "edit-del-3-c",
]
policies = ["deletion"]

[[experiment.ablation]]
mode = "ablation"
application = "websubmit"
app-config-override = "websubmit-strict"
feature-space-success = ["edit-del-1-a", "edit-del-2-a", "edit-del-3-a"]
feature-space-fail = [
    "edit-del-1-b",
    "edit-del-1-c",
    "edit-del-2-b",
    "edit-del-2-c",
    "edit-del-3-b",
    "edit-del-3-c",
]
policies = ["deletion"]

[[experiment.ablation]]
mode = "ablation"
application = "websubmit"
feature-space-success = ["edit-sc-1-a"]
feature-space-fail = ["edit-sc-1-b", "edit-sc-1-c"]
policies = ["scoped-storage"]

[[experiment.ablation]]
mode = "ablation"
application = "websubmit"
app-config-override = "websubmit-lib"
feature-space-success = ["edit-sc-1-a"]
feature-space-fail = ["edit-sc-1-b", "edit-sc-1-c"]
policies = ["scoped-storage"]

[[experiment.ablation]]
mode = "ablation"
application = "websubmit"
app-config-override = "websubmit-strict"
feature-space-success = ["edit-sc-1-a"]
feature-space-fail = ["edit-sc-1-b", "edit-sc-1-c"]
policies = ["scoped-storage"]

[[experiment.ablation]]
mode = "ablation"
application = "websubmit"
feature-space-success = ["edit-dis-1-a", "edit-dis-2-a", "edit-dis-3-a"]
feature-space-fail = [
    "edit-dis-1-b",
    "edit-dis-1-c",
    "edit-dis-2-b",
    "edit-dis-2-c",
    "edit-dis-3-b",
    "edit-dis-3-c",
]
policies = ["authorized-disclosure"]

[[experiment.ablation]]
mode = "ablation"
application = "websubmit"
app-config-override = "websubmit-lib"
feature-space-success = ["edit-dis-1-a", "edit-dis-2-a", "edit-dis-3-a"]
feature-space-fail = [
    "edit-dis-1-b",
    "edit-dis-1-c",
    "edit-dis-2-b",
    "edit-dis-2-c",
    "edit-dis-3-b",
    "edit-dis-3-c",
]
policies = ["authorized-disclosure"]

[[experiment.ablation]]
mode = "ablation"
application = "websubmit"
app-config-override = "websubmit-strict"
feature-space-success = ["edit-dis-1-a", "edit-dis-2-a", "edit-dis-3-a"]
feature-space-fail = [
    "edit-dis-1-b",
    "edit-dis-1-c",
    "edit-dis-2-b",
    "edit-dis-2-c",
    "edit-dis-3-b",
    "edit-dis-3-c",
]
policies = ["authorized-disclosure"]

[[experiment.plume-roll-forward]]
start-commit = "304fb740d8ba3aaae64b3eb67ecfe476841b87c4"
mode = "roll-forward"
application = "plume"
pass-threshold = ["e1777e9071b1b71fc164f88c74df56462ff11904"]
fail-threshold = []
app-config-override = "original-plume"
starting-expectation = "pass"
# From this one onwards compilation fails because the rustc versions are too different.
limit = 93

# [[experiment.atomic-roll-forward]]
# starting-commit = "79c9a91ae734ddd253d162a268de2a0365befcd7"
# mode = "roll-forward"
# application = "atomic-data"
# pass-threshold = ["46a503adbfc52678c97e52f6e8cfaf541aa6492d"]
# app-config-override = "original-atomic-data"
# starting-expectation = "pass"
# limit = 100
