stat-refresh-interval = "500ms"
paralegal-home-dir = "../paralegal"
pdg-timeout = "10min"

[app-config.lemmy]
source-dir = "case-studies/lemmy"
flow-args = ["--target", "lemmy_api"]
external-annotations = "external-annotations.toml"

[app-config.plume]
source-dir = "case-studies/plume"
external-annotations = "external-annotations.toml"
flow-args = ["--target", "plume-models"]
cargo-args = ["--no-default-features", "--features", "postgres"]

[app-config.websubmit]
source-dir = "case-studies/websubmit"
external-annotations = "baseline-external-annotations.toml"
cargo-args = ["--features", "v-ann-baseline"]

[app-config.websubmit-lib]
source-dir = "case-studies/websubmit"
external-annotations = "lib-external-annotations.toml"
cargo-args = ["--features", "v-ann-lib"]

[app-config.websubmit-strict]
source-dir = "case-studies/websubmit"
external-annotations = "strict-external-annotations.toml"
cargo-args = ["--features", "v-ann-strict"]

[app-config.freedit]
source-dir = "case-studies/freedit"
cargo-args = ["--lib"]
external-annotations = "external-annotations.toml"

[app-config.atomic-data]
source-dir = "case-studies/atomic-server"
external-annotations = "external-annotations.toml"
flow-args = ["--target", "atomic_lib"]
cargo-args = ["--lib", "--features", "db"]

[app-config.atomic-data.version-override.proc-macro2]
replacement = "1.0.78"
original = "1"

[app-config.hyperswitch]
source-dir = "case-studies/hyperswitch"
external-annotations = "external-annotations.toml"
flow-args = ["--target", "--router"]
cargo-args = ["--lib"]

[app-config.original-plume]
# Must point to a directory containing the https://github.com/Plume-org/Plume
# git repository
source-dir = "../../clones/Plume"
external-annotations = "../../research/dfpp-verification/roll-forward/original-plume-external-annotations.toml"
flow-args = [
    "--target",
    "plume-models",
    "--analyze",
    "crate::users::User::delete",
]
cargo-args = ["--no-default-features", "--features", "postgres"]


[app-config.original-plume.version-override.proc-macro2]
replacement = "1.0.78"
original = "1"

[app-config.roll-forward-atomic]
# Must point to a directory containing the
# https://github.com/atomicdata-dev/atomic-server git repository
source-dir = "../../clones/atomic-server"
external-annotations = "../../research/dfpp-verification/roll-forward/atomic/external-annotations.toml"
flow-args = [
    "--target",
    "atomic_lib",
    "--analyze",
    "crate::commit::Commit::apply_opts",
]
cargo-args = ["--lib", "--features", "db"]

[app-config.roll-forward-atomic-22ba25abd1177e1453042a395ef2bc2a35338b78]
# Must point to a directory containing the
# https://github.com/atomicdata-dev/atomic-server git repository
source-dir = "../../clones/atomic-server"
external-annotations = "../../research/dfpp-verification/roll-forward/atomic/22ba25abd1177e1453042a395ef2bc2a35338b78-external-annotations.toml"
flow-args = [
    "--target",
    "atomic_lib",
    "--analyze",
    "crate::commit::Commit::apply_opts",
]
cargo-args = ["--lib", "--features", "db"]

[app-config.original-atomic-data.version-override.proc-macro2]
replacement = "1.0.78"
original = "1"

[[experiment.case-studies]]
mode = "case-study"
application = "lemmy"

[[experiment.case-studies]]
mode = "case-study"
application = "plume"

[[experiment.case-studies]]
mode = "case-study"
application = "freedit"

[[experiment.case-studies]]
mode = "case-study"
application = "websubmit"

[[experiment.case-studies]]
mode = "case-study"
application = "atomic-data"

# Need to debug the policy/app
# [[experiment.case-studies]]
# mode = "case-study"
# application = "hyperswitch"

[[experiment.adaptive-depth]]
mode = "case-study"
application = "lemmy"
adaptive-depth = false

[[experiment.ablation]]
mode = "ablation"
application = "websubmit"
feature-space-success = ["edit-del-1-a", "edit-del-2-a", "edit-del-3-a"]
feature-space-fail = [
    "edit-del-1-b",
    "edit-del-1-c",
    "edit-del-2-b",
    "edit-del-2-c",
    "edit-del-3-b",
    "edit-del-3-c",
]
policies = ["deletion"]

[[experiment.ablation]]
mode = "ablation"
application = "websubmit"
app-config-override = "websubmit-lib"
feature-space-success = ["edit-del-1-a", "edit-del-2-a", "edit-del-3-a"]
feature-space-fail = [
    "edit-del-1-b",
    "edit-del-1-c",
    "edit-del-2-b",
    "edit-del-2-c",
    "edit-del-3-b",
    "edit-del-3-c",
]
policies = ["deletion"]

[[experiment.ablation]]
mode = "ablation"
application = "websubmit"
app-config-override = "websubmit-strict"
feature-space-success = ["edit-del-1-a", "edit-del-2-a", "edit-del-3-a"]
feature-space-fail = [
    "edit-del-1-b",
    "edit-del-1-c",
    "edit-del-2-b",
    "edit-del-2-c",
    "edit-del-3-b",
    "edit-del-3-c",
]
policies = ["deletion"]

[[experiment.ablation]]
mode = "ablation"
application = "websubmit"
feature-space-success = ["edit-sc-1-a"]
feature-space-fail = ["edit-sc-1-b", "edit-sc-1-c"]
policies = ["scoped-storage"]

[[experiment.ablation]]
mode = "ablation"
application = "websubmit"
app-config-override = "websubmit-lib"
feature-space-success = ["edit-sc-1-a"]
feature-space-fail = ["edit-sc-1-b", "edit-sc-1-c"]
policies = ["scoped-storage"]

[[experiment.ablation]]
mode = "ablation"
application = "websubmit"
app-config-override = "websubmit-strict"
feature-space-success = ["edit-sc-1-a"]
feature-space-fail = ["edit-sc-1-b", "edit-sc-1-c"]
policies = ["scoped-storage"]

[[experiment.ablation]]
mode = "ablation"
application = "websubmit"
feature-space-success = ["edit-dis-1-a", "edit-dis-2-a", "edit-dis-3-a"]
feature-space-fail = [
    "edit-dis-1-b",
    "edit-dis-1-c",
    "edit-dis-2-b",
    "edit-dis-2-c",
    "edit-dis-3-b",
    "edit-dis-3-c",
]
policies = ["authorized-disclosure"]

[[experiment.ablation]]
mode = "ablation"
application = "websubmit"
app-config-override = "websubmit-lib"
feature-space-success = ["edit-dis-1-a", "edit-dis-2-a", "edit-dis-3-a"]
feature-space-fail = [
    "edit-dis-1-b",
    "edit-dis-1-c",
    "edit-dis-2-b",
    "edit-dis-2-c",
    "edit-dis-3-b",
    "edit-dis-3-c",
]
policies = ["authorized-disclosure"]

[[experiment.ablation]]
mode = "ablation"
application = "websubmit"
app-config-override = "websubmit-strict"
feature-space-success = ["edit-dis-1-a", "edit-dis-2-a", "edit-dis-3-a"]
feature-space-fail = [
    "edit-dis-1-b",
    "edit-dis-1-c",
    "edit-dis-2-b",
    "edit-dis-2-c",
    "edit-dis-3-b",
    "edit-dis-3-c",
]
policies = ["authorized-disclosure"]

[[experiment.plume-roll-forward-1]]
start = "304fb740d8ba3aaae64b3eb67ecfe476841b87c4"
end = "e1777e9071b1b71fc164f88c74df56462ff11904"
mode = "roll-forward"
application = "plume"
app-config-override = "original-plume"
expectation = "pass"

[[experiment.plume-roll-forward-2]]
start = "613ccbcd945618cce624725aee3e2997cbf6de38"
# From this one onwards compilation fails because the rustc versions are too different.
end = "08cd777f8146c4a619a8615d091ef22901ed0b58"
mode = "roll-forward"
application = "plume"
app-config-override = "original-plume"
expectation = "fail"

# Contains the ranges for atomic's roll forward experiment in order. See
# https://www.notion.so/justus-adam/Roll-forward-experiment-on-5706ecdd8c7045ca9f3a9e3a4603e2fe?pvs=4
# for an overview table
[[experiment.atomic-roll-forward-c97cde6567d49ae0eab6e94130748560660ba830]]
start = "c97cde6567d49ae0eab6e94130748560660ba830"
end = "aba49fefb6e6e7def4faed4542b3436a358ef56f"
mode = "roll-forward"
application = "atomic-data"
app-config-override = "roll-forward-atomic"
expectation = "pass"

[[experiment.atomic-roll-forward-22ba25abd1177e1453042a395ef2bc2a35338b78]]
start = "22ba25abd1177e1453042a395ef2bc2a35338b78"
end = "46a503adbfc52678c97e52f6e8cfaf541aa6492d"
mode = "roll-forward"
application = "atomic-data"
app-config-override = "roll-forward-atomic-22ba25abd1177e1453042a395ef2bc2a35338b78"
expectation = "pass"

[[experiment.atomic-roll-forward-bae7b97ff105181fce48947163a48e9b50433953]]
start = "bae7b97ff105181fce48947163a48e9b50433953"
end = "9745069392e25d70cf159fadcab6d2c22949fa49"
mode = "roll-forward"
application = "atomic-data"
app-config-override = "roll-forward-atomic-22ba25abd1177e1453042a395ef2bc2a35338b78"
expectation = "fail"
