stat-refresh-interval = "500ms"
paralegal-home-dir = "../paralegal"
# Bumped because lemmy without adaptive depth takes ~10min in analysis
pdg-timeout = "15min"

[app-config.lemmy]
source-dir = "case-studies/lemmy"
flow-args = ["--target", "lemmy_api"]
external-annotations = "external-annotations.toml"

[app-config.plume]
source-dir = "case-studies/plume"
external-annotations = "external-annotations.toml"
flow-args = ["--target", "plume-models"]
cargo-args = ["--no-default-features", "--features", "postgres"]

[app-config.websubmit]
source-dir = "case-studies/websubmit"
external-annotations = "baseline-external-annotations.toml"

[app-config.websubmit-lib]
source-dir = "case-studies/websubmit"
external-annotations = "lib-external-annotations.toml"

[app-config.websubmit-strict]
source-dir = "case-studies/websubmit"
external-annotations = "strict-external-annotations.toml"

[app-config.freedit]
source-dir = "case-studies/freedit"
cargo-args = ["--lib"]
external-annotations = "external-annotations.toml"

[app-config.atomic-data]
source-dir = "case-studies/atomic-server"
external-annotations = "external-annotations.toml"
flow-args = ["--target", "atomic_lib"]
cargo-args = ["--lib", "--features", "db"]

[app-config.atomic-data.version-override.proc-macro2]
replacement = "1.0.78"
original = "1"

[app-config.hyperswitch]
source-dir = "case-studies/hyperswitch"
external-annotations = "external-annotations.toml"
# There is a linker bug which triggers on transitive invocation of our
# plugin in Hyperswitches build script. The --rustc-reset-for-linux overrides
# environment variables set by cargo to use the "stock rustc" on such repeat
# invocations. This is a hack that we only do here, becaus it could have other
# incpatibility issues in other libraries if they rely on the rustc to be the
# same version.
flow-args = ["--target", "router", "--rustc-reset-for-linux"]
cargo-args = ["--lib"]

[app-config.contile]
source-dir = "case-studies/contile"
external-annotations = "external-annotations.toml"
cargo-args = ["--lib"]

[app-config.original-plume]
# Must point to a directory containing the https://github.com/Plume-org/Plume
# git repository
#
# If the directory does not exist, the runner will to auto-clone. The parent
# directory must exist however
source-dir = "../../clones/Plume"
clone = "https://github.com/Plume-org/Plume"
flow-args = [
    "--target",
    "plume-models",
    "--analyze",
    "crate::users::User::delete",
]
cargo-args = ["--no-default-features", "--features", "postgres"]


[app-config.original-plume.version-override.proc-macro2]
replacement = "1.0.78"
original = "1"

[app-config.roll-forward-atomic]
# Must point to a directory containing the
# https://github.com/atomicdata-dev/atomic-server git repository
#
# If the directory does not exist, the runner will to auto-clone. The parent
# directory must exist however
source-dir = "../../clones/atomic-server"
clone = "https://github.com/atomicdata-dev/atomic-server"
flow-args = [
    "--target",
    "atomic_lib",
    "--analyze",
    "crate::commit::Commit::apply_opts",
]
cargo-args = ["--lib", "--features", "db"]


[[experiment.case-studies]]
mode = "case-study"
application = "plume"
policy-mode = "unified"

[[experiment.case-studies]]
mode = "case-study"
application = "freedit"
policy-mode = "unified"

[[experiment.case-studies]]
mode = "case-study"
application = "websubmit"
policy-mode = "unified"

[[experiment.case-studies]]
mode = "case-study"
application = "atomic-data"
policy-mode = "unified"

[[experiment.case-studies]]
mode = "case-study"
application = "lemmy"
lemmy-controller-run-mode = "all"
policy-mode = "unified"
bugs = ["bug4"]

[[experiment.case-studies]]
mode = "case-study"
application = "hyperswitch"
# Limiting policies for now, because only these actually make sense
policies = ["card-storage", "apikey-storage"]
policy-mode = "unified"

[[experiment.case-studies]]
mode = "case-study"
application = "contile"
# Otherwise we overtaint and don't pass the non-bug
policy-mode = "unified"


[[experiment.per-controller]]
mode = "case-study"
application = "plume"
policy-mode = "unified"
controller-run-mode = "affected"
adaptive-depth = false

[[experiment.per-controller]]
mode = "case-study"
application = "freedit"
policy-mode = "unified"
controller-run-mode = "affected"
adaptive-depth = false

[[experiment.per-controller]]
mode = "case-study"
application = "websubmit"
policy-mode = "unified"
controller-run-mode = "affected"
adaptive-depth = false

[[experiment.per-controller]]
mode = "case-study"
application = "atomic-data"
policy-mode = "unified"
controller-run-mode = "affected"
adaptive-depth = false

[[experiment.per-controller]]
mode = "case-study"
application = "lemmy"
lemmy-controller-run-mode = "all"
policy-mode = "unified"
bugs = ["bug4"]
controller-run-mode = "affected"
adaptive-depth = false

[[experiment.per-controller]]
mode = "case-study"
application = "hyperswitch"
# Limiting policies for now, because only these actually make sense
policies = ["card-storage", "apikey-storage"]
policy-mode = "unified"
controller-run-mode = "affected"
adaptive-depth = false

[[experiment.per-controller]]
mode = "case-study"
application = "contile"
# Otherwise we overtaint and don't pass the non-bug
policy-mode = "unified"
controller-run-mode = "affected"
adaptive-depth = false
