[["atomic_lib::commit::Commit::into_resource"]]
marker = "resource"
on_return = true

[["atomic_lib::storelike::Storelike::get_resource"]]
marker = "resource"
on_return = true

[["atomic_lib::hierarchy::check_rights"]]
marker = "check_rights"
on_argument = [1]

[["atomic_lib::commit::Commit::apply_changes"]]
marker = "new_resource"
on_return = true

[["atomic_lib::resources::Resource::set_propval"]]
marker = "new_resource"
on_argument = [1]

[["atomic_lib::storelike::Storelike::add_resource"]]
marker = "sink"
on_argument = [1]

[["atomic_lib::storelike::Storelike::add_resource_opts"]]
marker = "sink"
on_argument = [1]

[["atomic_lib::storelike::Storelike::handle_commit"]]
marker = "sink"
on_argument = [1]

[["atomic_lib::storelike::Storelike::get_resource"]]
marker = "noinline"

[["atomic_lib::resources::Resource::get"]]
marker = "noinline"

[["atomic_lib::resources::Resource::get_classes"]]
marker = "noinline"

[["atomic_lib::storelike::Storelike::handle_commit"]]
marker = "noinline"

[["atomic_lib::plugins::chatroom::after_apply_commit_message"]]
marker = "noinline"
