[["lemmy_api::lemmy_api_common::utils::check_community_deleted_or_removed"]]
marker = "delete_check"
on_return = true

[["lemmy_api::lemmy_api_common::utils::check_community_ban"]]
marker = "ban_check"
on_return = true

[["lemmy_api::lemmy_api_common::utils::check_user_valid"]]
marker = "ban_check"
on_return = true

[["lemmy_api::lemmy_api_common::utils::check_user_valid"]]
marker = "delete_check"
on_return = true

[["diesel::update"]]
marker = "db"
on_return = true

[["diesel::delete"]]
marker = "db"
on_return = true

[["diesel::insert_into"]]
marker = "db"
on_return = true