[["lemmy_api_common::utils::check_community_deleted_or_removed"]]
marker = "delete_check"
on_return = true

[["lemmy_api_common::utils::check_community_ban"]]
marker = "ban_check"
on_return = true

[["lemmy_api_common::utils::check_user_valid"]]
marker = "ban_check"
on_argument = [0]

[["lemmy_api_common::utils::check_user_valid"]]
marker = "delete_check"
on_argument = [2]

# apub specific
[["lemmy_apub::activities::check_community_deleted_or_removed"]]
marker = "delete_check"
on_argument = [0]

[["lemmy_apub::activities::verify_person_in_community"]]
marker = "ban_check"
on_argument = [1]