[["blake3::keyed_hash"]]
marker = "hashed"
on_return = true

[["api_models::payments::Card"]]
marker = "credit_card"

[["common_enums::FutureUsage"]]
marker = "future_usage_decision"

# [["common_enums::DbFutureUsage"]]
# marker = "future_usage_decision"

# [["crate::core::mandate::MandateBehaviour::get_setup_future_usage"]]
# marker = "future_usage_decision"
# on_return = true

[["router::services::api::ApplicationResponse"]]
marker = "externalize"

[["api_models::api_keys::CreateApiKeyResponse"]]
marker = "apikey_response"

[["router::db::api_keys::ApiKeyInterface::insert_api_key"]]
marker = "externalize"
on_argument = [1]
