
[["diesel::query_builder::functions::insert_into"]]
markers = ["db_access", "instance"]
on_return = true

# [["lemmy_db_schema::schema::site::table"]]
# marker = "db_access"

# [["lemmy_db_schema::schema::local_user::table"]]
# marker = "db_access"

[["lemmy_db_views::local_user_view::LocalUserView::find_by_email_or_name"]]
markers = ["db_access", "instance", "instance_safe"]
on_return = true

[["lemmy_db_views::structs::LocalUserView::read_person"]]
markers = ["db_access", "instance"]
on_return = true

[["lemmy_db_schema::impls::site::Site::read_local_site"]]
markers = ["db_access", "instance"]
on_return = true

[["lemmy_api_common::utils::check_user_valid"]]
markers = ["instance_ban_check", "instance_delete_check"]
on_return = true

[["lemmy_db_views::structs::CommentView::read"]]
markers = ["db_access", "instance"]
on_return = true

[["<lemmy_db_schema::source::comment::CommentLike as lemmy_db_schema::traits::Likeable>::remove"]]
markers = ["db_access", "community", "instance"]
on_return = true

[["<lemmy_db_schema::source::comment::CommentLike as lemmy_db_schema::traits::Likeable>::like"]]
markers = ["db_access", "community", "instance"]
on_return = true

[["lemmy_api_common::utils::check_community_deleted_or_removed"]]
marker = "community_delete_check"
on_return = true

[["lemmy_api_common::utils::check_community_ban"]]
marker = "community_ban_check"
on_return = true

[["lemmy_db_schema::source::comment::Comment::update_read"]]
on_return = true
markers = ["db_access", "community", "instance"]

[["<lemmy_db_schema::source::comment::CommentSaved as lemmy_db_schema::traits::Saveable>::save"]]
markers = ["db_access", "community", "instance"]
on_return = true

[["<lemmy_db_schema::source::comment::CommentSaved as lemmy_db_schema::traits::Saveable>::unsave"]]
markers = ["db_access", "community", "instance"]
on_return = true

[["<lemmy_db_schema::source::comment_report::CommentReport as lemmy_db_schema::traits::Reportable>::report"]]
markers = ["db_access", "community", "instance"]
on_return = true

[["lemmy_db_views::structs::CommentReportView::read"]]
markers = ["db_access", "instance"]
on_return = true

[["lemmy_db_views::comment_report_view::CommentReportQueryBuilder::create"]]
markers = ["db_access", "instance"]
on_return = true

[["<lemmy_db_schema::source::community::Community as lemmy_db_schema::traits::Crud>::read"]]
markers = ["db_access", "instance"]
on_return = true

[["<lemmy_db_schema::source::community::CommunityModerator as lemmy_db_schema::traits::Joinable>::join"]]
markers = ["db_access", "instance", "community"]
on_return = true

[["<lemmy_db_schema::source::community::CommunityModerator as lemmy_db_schema::traits::Joinable>::leave"]]
markers = ["db_access", "instance", "community"]
on_return = true

[["<lemmy_db_schema::source::moderator::ModAddCommunity as lemmy_db_schema::traits::Crud>::create"]]
markers = ["db_access", "instance", "community"]
on_return = true

[["<lemmy_db_schema::source::person::Person as lemmy_db_schema::traits::Crud>::read"]]
markers = ["db_access", "instance"]
on_return = true

[["lemmy_db_views_actor::structs::CommunityModeratorView::for_community"]]
markers = ["db_access", "instance"]
on_return = true

[["<lemmy_db_schema::source::community::CommunityPersonBan as lemmy_db_schema::traits::Bannable>::ban"]]
markers = ["db_access", "instance", "community"]
on_return = true

[["<lemmy_db_schema::source::community::CommunityPersonBan as lemmy_db_schema::traits::Bannable>::unban"]]
markers = ["db_access", "instance", "community"]
on_return = true

[["<lemmy_db_schema::source::community::CommunityFollower as lemmy_db_schema::traits::Followable>::unfollow"]]
markers = ["db_access", "instance", "community"]
on_return = true

[["<lemmy_db_schema::source::moderator::ModBanFromCommunity as lemmy_db_schema::traits::Crud>::create"]]
markers = ["db_access", "instance", "community"]
on_return = true

[["lemmy_db_views_actor::structs::PersonViewSafe::read"]]
markers = ["db_access", "instance"]
on_return = true

[["lemmy_api_common::utils::remove_user_data_in_community"]]
markers = ["db_access", "instance", "community"]
on_return = true

[["<lemmy_db_schema::source::community_block::CommunityBlock as lemmy_db_schema::traits::Blockable>::block"]]
markers = ["db_access", "instance", "community"]
on_return = true

[["<lemmy_db_schema::source::community_block::CommunityBlock as lemmy_db_schema::traits::Blockable>::unblock"]]
markers = ["db_access", "instance", "community"]
on_return = true

[["lemmy_db_views_actor::structs::CommunityView::read"]]
markers = ["db_access", "instance"]
on_return = true
