[["alloc::vec::Vec::new"]]
marker = "safe_source"
on_return = true

[["core::iter::traits::collect::IntoIterator::into_iter"]]
marker = "no_skip"
on_return = true
on_argument = [0]

[["core::iter::traits::iterator::Iterator::next"]]
marker = "no_skip"
on_return = true
on_argument = [0]

[["std::io::_print"]]
marker = "sink"
on_argument = [0]

[["alloc::vec::Vec::append"]]
marker = "not_safe_source"
on_return = true

[["alloc::vec::Vec::append"]]
marker = "not_safe_source"
on_argument = [0, 1]

# uncommenting the below code will allow dis-1-c to be caught but dis-2-a to fail.
# [["alloc::vec::Vec::push"]]
# marker = "not_safe_source"
# on_return = true

# [["alloc::vec::Vec::push"]]
# marker = "not_safe_source"
# on_argument = [0, 1]

[["std::string::ToString::to_string"]]
marker = "benign"
on_argument = [0]
on_return = true

[["std::clone::Clone::clone"]]
marker = "benign"
on_argument = [0]
on_return = true

[["std::string::String::as_str"]]
marker = "benign"
on_argument = [0]
on_return = true

[["std::convert::Into::into"]]
marker = "benign"
on_argument = [0]
on_return = true

[["slice::into_vec"]]
marker = "benign"
on_argument = [0]
on_return = true
